c8amovies/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from media.views import Principal
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('videos/', include('media.urls')),
    path('', Principal.as_view(), name='home')
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

media/urls.py
from django.urls import path, include

#importando la vista principal
from .views import Principal
from .views import RegistrarUsuario, Login, Logout
from .views import DetalleCatalogo, ver_video, ver_image_video, ver_image_catalogo
from .views import VideoCap, ver_video_cap, guardar_visualizaciones



app_name='video'
urlpatterns=[
    path('index/', Principal.as_view(), name='index'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('registrar_usuario/', RegistrarUsuario.as_view(), name='registrar'),
    path('detallecatalogo/<slug:url>/<int:pk>', DetalleCatalogo.as_view(), name='detallecatalog'),
    path('ver-video/<int:pk>', ver_video, name='view_video'),
    path('ver-image-video/<int:pk>', ver_image_video, name='view_img_video'),
    path('ver-image-catalogo/<int:pk>', ver_image_catalogo, name='view_img_catalog'),
    path('capitulo/<int:pk>', VideoCap.as_view(), name='view_video_cap'),
    path('ver-video-cap/<int:pk>', ver_video_cap, name='view_cap'),
    path('guardar_visualizaciones/', guardar_visualizaciones, name='save_video_view')
]

media/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.urls import reverse_lazy
from django.utils.text import slugify

import hashlib
# Create your models here.

class UserManager(UserManager):
    def get_by_natural_key(self, username):
        return self.get(username=username)

class User(AbstractUser):
    objects=UserManager()
    fecha_nacimiento=models.DateField(null=True, blank=True)
    telefono=models.CharField(help_text='Ingrese su numero de Telefono', max_length=8, null=True)
    
    class Meta:
        db_table='auth_user'
    
    def natural_key(self):
        return self.username


class CategoriaCatalogo(models.Model):
    categoria=models.CharField(help_text='Ingrese la categoria de la pelicula, serie o video, como niños, adultos, etc', max_length=100)
    
    def __str__(self):
        return self.categoria

class ClasificacionCatalogo(models.Model):
    clasificacion=models.CharField(max_length=10, help_text='Ingrese la clasificacion de la pelicula serie o novela, como A, B, C')
    
    def __str__(self):
        return self.clasificacion


class TipoCatalog(models.Model):
    tipo=models.CharField(max_length=20, help_text='Ingrese el tipo de catalogo como novela, serie, pelicula')

    def __str__(self):
        return self.tipo

class CatalogoVideo(models.Model):
    catalog_nombre=models.CharField(help_text='Ingrese el nombre de la serie novela o pelicula', max_length=100)
    sipnosis=models.TextField(help_text='Ingrese la sipnosis de la novela o serie o pelicula')
    author=models.CharField(help_text='Ingrese el nombre del autor', max_length=50)
    url=models.SlugField(max_length=200, help_text='url del catalogo', null=True, blank=True)
    nocap=models.IntegerField(help_text='Ingrese la cantidad de capitulos que tiene la pelicula o o serie')
    videotriller=models.FileField(upload_to='video_triller', null=True)
    img_presentacion=models.ImageField(upload_to='img_pre')
    idcategoria=models.ForeignKey(CategoriaCatalogo, on_delete=models.CASCADE, help_text='Ingrese el tipo de catalogo')
    idclasificacion=models.ForeignKey(ClasificacionCatalogo, on_delete=models.CASCADE, help_text='Ingrese la clasificacion, del video')
    idtipo=models.ForeignKey(TipoCatalog, on_delete=models.CASCADE, help_text='Ingrese el tipo de video')
    anio_lanza=models.CharField(max_length=5, null=True, blank=True)
    fecha_publicacion=models.DateTimeField(auto_now_add=True, blank=True, null=True)
    urlencrip=models.TextField(null=True, blank=True, help_text='ingrese la url encriptada');
    def __str__(self):
        return "%s, %s"%(self.catalog_nombre, self.sipnosis)

    def get_absolute_url(self):
        return reverse_lazy('video:detallecatalog', args=[str(self.url), str(self.pk)])
    
    def get_slug(self):
        return self.url

    def save(self, *args, **kwargs):
        self.url=slugify(self.catalog_nombre[:200])
        encrip=hashlib.new('sha256', self.url.encode('utf-8'))
        self.urlencrip=encrip.digest()
        super(CatalogoVideo, self).save(*args, **kwargs)

class TemporadaVideo(models.Model):
    temporada=models.CharField(help_text="Ingrese el numero de temporada", max_length=50)

    def __str__(self):
        return "%s"%self.temporada


class Videos(models.Model):
    descripcion=models.CharField(max_length=50, help_text='Ingrese el nombre del video', null=True, blank=True)
    cap=models.CharField(help_text="Ingrese el numero de capitulo", max_length=50)
    idtemporada=models.ForeignKey(TemporadaVideo, on_delete=models.CASCADE, help_text='Ingrese la temporada del video', null=True)
    idcatalog=models.ForeignKey(CatalogoVideo ,help_text="Ingrese el catalogo al que pertenece el video", on_delete=models.CASCADE)
    video=models.FileField(upload_to='videos')
    miniatura=models.ImageField(upload_to="mini_img_video")

    def __str__(self):
        return "cap %s"%self.cap

class Visualizaciones(models.Model):
    idusuario=models.ForeignKey(User, on_delete=models.CASCADE, help_text="Ingrese el id del usuario")
    video=models.ForeignKey(Videos, on_delete=models.CASCADE, help_text='Ingrese el Video a visualizar')
    hora=models.CharField(max_length=4, help_text="Ingrese la hora en que termino de ver el video", null=True, blank=True)
    minuto=models.CharField(max_length=4, help_text='Ingrese el minuto en que dejo de ver el video', null=True, blank=True)
    segundo=models.CharField(max_length=4, help_text='Ingrese el segundo en que se quedo el video', null=True, blank=True)
    fecha_visualizacion=models.DateField(auto_now_add=True, help_text='Ingrese la fecha de visualizacion')

    def __str__(self):
        return "visualizacion %s %s"%(self.video, self.idusuario)

media/forms.py
from django import forms
from django.contrib.admin import widgets as wd
from django.contrib.auth.forms import UserCreationForm
from django.db import models
from django.forms import widgets
from .models import User
from django.contrib.auth.forms import AuthenticationForm

class UserForm(UserCreationForm):
    class Meta:
        model=User
        fields=('username', 'email', 'first_name', 'last_name', 'telefono')

        labels={
            'username':'Nombre de Usuario',
            'email':'Correo Electronico',
            'first_name':'Nombres',
            'last_name':'Apellidos',
            'telefono':'Telefono'
        }

        widgets={
            'username':wd.AdminTextInputWidget,
            'email':wd.AdminEmailInputWidget,
            'first_name':wd.AdminTextInputWidget,
            'last_name':wd.AdminTextInputWidget,
            'telefono':wd.AdminTextInputWidget
        }

media/views.py
from django.shortcuts import render

from django.views.generic import TemplateView
from media.proces_usuario.crud_usuario import RegistrarUsuario
from media.proces_usuario.crud_usuario import Login, Logout
from media.proces_catalogo.crud_catalogo import DetalleCatalogo, ver_video, ver_image_video, ver_image_catalogo
from media.proces_video.crud_video import VideoCap, ver_video_cap, guardar_visualizaciones
#obteniendo el modelo de catalogo
from .models import CatalogoVideo, CategoriaCatalogo

from django.http import Http404

from django.core.paginator import Paginator


# Create your views here.

class Principal(TemplateView):
    template_name='media/index.html'

    def paginar_catalogos(self, catalogos, page):
        cata=None
        paginator=None
        datos={}
        try:
            paginator=Paginator(catalogos, 20)
            cata=paginator.page(page)
            datos['paginator']=paginator
            datos['cata']=cata
        except:
            raise Http404
        return datos

    def get_context_data(self, **kwargs):
        context=super(Principal, self).get_context_data(**kwargs)

        categorias=CategoriaCatalogo.objects.all()

        catalogos_x_categorias={}
        catalog=CatalogoVideo.objects.all()
        for cate in categorias:
            catalogos=CatalogoVideo.objects.filter(idcategoria__id=cate.pk)
            catalogos_x_categorias[cate.categoria]=catalogos

        context['catalog_cate']=catalogos_x_categorias
        
        return context

media/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
  <!-- Google Fonts -->
  <link
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    rel="stylesheet"
  />
  <!-- MDB -->
  <link
    href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
    rel="stylesheet"
  />
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/estilos.css' %}">
    {% block titulo %}

    {% endblock %}
</head>
<body>
    <div class="container">
            <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <!-- Container wrapper -->
        <div class="container-fluid">
        <!-- Toggle button -->
        <button
            class="navbar-toggler"
            type="button"
            data-mdb-toggle="collapse"
            data-mdb-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <i class="fas fa-bars"></i>
        </button>
    
        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Navbar brand -->
            <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'video:index' %}">
            <img
                src="https://mdbootstrap.com/img/logo/mdb-transaprent-noshadows.png"
                height="15"
                alt=""
                loading="lazy"
            />
            </a>
            <!-- Left links -->
            {% if user.is_authenticated %}
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Peliculas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Novelas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Series</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Niños</a>
                    </li>
                </ul>
            {% else %}
                 <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'video:registrar' %}">Registrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'video:login' %}">Iniciar sesión</a>
                    </li>
                </ul>           
            {% endif %}
            <!-- Left links -->
        </div>
        <!-- Collapsible wrapper -->
    
        <!-- Right elements -->
        <div class="d-flex align-items-center">
            <form class="d-flex input-group w-auto">
                <input
                  type="search"
                  class="form-control rounded"
                  placeholder="Search"
                  aria-label="Search"
                  aria-describedby="search-addon"
                />
                <span class="input-group-text border-0" id="search-addon">
                  <i class="fas fa-search"></i>
                </span>
              </form>    
            <!-- Notifications -->
            <a
            class="text-reset me-3 dropdown-toggle hidden-arrow"
            href="#"
            id="navbarDropdownMenuLink"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
            >
            <i class="fas fa-bell"></i>
            <span class="badge rounded-pill badge-notification bg-danger">1</span>
            </a>
            <ul
            class="dropdown-menu dropdown-menu-end"
            aria-labelledby="navbarDropdownMenuLink"
            >
            <li>
                <a class="dropdown-item" href="#">Some news</a>
            </li>
            <li>
                <a class="dropdown-item" href="#">Another news</a>
            </li>
            <li>
                <a class="dropdown-item" href="#">Something else here</a>
            </li>
            </ul>

    
            <!-- Avatar -->
            <a
            class="dropdown-toggle d-flex align-items-center hidden-arrow"
            href="#"
            id="navbarDropdownMenuLink"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
            >
            <img
                src="https://mdbootstrap.com/img/new/avatars/2.jpg"
                class="rounded-circle"
                height="25"
                alt=""
                loading="lazy"
            />
            </a>
            <ul
            class="dropdown-menu dropdown-menu-end"
            aria-labelledby="navbarDropdownMenuLink"
            >
            <li>
                <a class="dropdown-item" href="#">My profile</a>
            </li>
            <li>
                <a class="dropdown-item" href="#">Settings</a>
            </li>
            <li>
                <a class="dropdown-item" href="{% url 'video:logout' %}">Logout</a>
            </li>
            </ul>
        </div>
        <!-- Right elements -->
        </div>
        <!-- Container wrapper -->
    </nav>
    <!-- Navbar --> 
    {% block contenido %}
        
            <div class="containe-fluid">
                {# todos el  contenido #}               
                    <ul class="list-group">
                        {% if catalog_cate %}
                            {% for k, v in catalog_cate.items %}
                              <li class="list-group-item active" aria-current="true">{{ k }}</li>
                              <li class="list-group-item">
                                <div class="row row-cols-1 row-cols-md-4 row-cols-sm-1 rows-cols-lg-4 row-cols-xl-4 g-4" style="height:53vh; overflow-x:scroll;">
                                  {% for listvideo in v %}
                                  <div class="col">
                                    <div class="card h-100">
                                        <a href="{% url 'video:detallecatalog' url=listvideo.url pk=listvideo.id  %}">
                                            <img
                                            src="{% url 'video:view_img_catalog' listvideo.pk %}"
                                            class="card-img-top"
                                            alt="..."
                                          />                              
                                        </a>
                                      <div class="card-body">
                                        <h5 class="card-title">{{ listvideo.catalog_nombre }}</h5>
                                      </div>
                                      <div class="card-footer">
                                        <small class="text-muted">publicado el {{ listvideo.fecha_publicacion }}</small>
                                      </div>
                                    </div>
                                  </div>
                                    {% endfor %}
                                </div>
                                {% include "media/paginator.html" %}                           
                              </li>
                            {% endfor %}
                        {% endif %}
                    </ul>


            </div>
        
    {% endblock %}

    <!-- Footer -->
    <footer class="text-center text-lg-start bg-light text-muted">
        <!-- Section: Social media -->
        <section
        class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
        >
        <!-- Left -->
        <div class="me-5 d-none d-lg-block">
            <span>Get connected with us on social networks:</span>
        </div>
        <!-- Left -->
    
        <!-- Right -->
        <div>
            <a href="" class="me-4 text-reset">
            <i class="fab fa-facebook-f"></i>
            </a>
            <a href="" class="me-4 text-reset">
            <i class="fab fa-twitter"></i>
            </a>
            <a href="" class="me-4 text-reset">
            <i class="fab fa-google"></i>
            </a>
            <a href="" class="me-4 text-reset">
            <i class="fab fa-instagram"></i>
            </a>
            <a href="" class="me-4 text-reset">
            <i class="fab fa-linkedin"></i>
            </a>
            <a href="" class="me-4 text-reset">
            <i class="fab fa-github"></i>
            </a>
        </div>
        <!-- Right -->
        </section>
        <!-- Section: Social media -->
    
        <!-- Section: Links  -->
        <section class="">
        <div class="container text-center text-md-start mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
            <!-- Grid column -->
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                <!-- Content -->
                <h6 class="text-uppercase fw-bold mb-4">
                <i class="fas fa-gem me-3"></i>Company name
                </h6>
                <p>
                Here you can use rows and columns to organize your footer content. Lorem ipsum
                dolor sit amet, consectetur adipisicing elit.
                </p>
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">
                Products
                </h6>
                <p>
                <a href="#!" class="text-reset">Angular</a>
                </p>
                <p>
                <a href="#!" class="text-reset">React</a>
                </p>
                <p>
                <a href="#!" class="text-reset">Vue</a>
                </p>
                <p>
                <a href="#!" class="text-reset">Laravel</a>
                </p>
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">
                Useful links
                </h6>
                <p>
                <a href="#!" class="text-reset">Pricing</a>
                </p>
                <p>
                <a href="#!" class="text-reset">Settings</a>
                </p>
                <p>
                <a href="#!" class="text-reset">Orders</a>
                </p>
                <p>
                <a href="#!" class="text-reset">Help</a>
                </p>
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">
                Contact
                </h6>
                <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
                <p>
                <i class="fas fa-envelope me-3"></i>
                info@example.com
                </p>
                <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
                <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
            </div>
            <!-- Grid column -->
            </div>
            <!-- Grid row -->
        </div>
        </section>
        <!-- Section: Links  -->
    
        <!-- Copyright -->
        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
        © 2021 Copyright:
        <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
        </div>
        <!-- Copyright -->
    </footer>
  <!-- Footer -->
    </div>
<!-- MDB -->
    <script
    type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
    ></script>
    <link href="https://vjs.zencdn.net/7.15.4/video-js.css" rel="stylesheet" />

    {% block scriptjs %}
    {% load static  %}
    <script type="text/javascript" src="{% static 'js/control_base.js' %}"></script>
    {% endblock%}
</body>
</html>

media/templates/media/index.html
{% extends "base.html" %}

media/templates/media/proces_catalogo/detalle_catalogo_video.html
{% extends "base.html" %}

{% block titulo %}
	<title>{{ detallevideo.catalog_nombre }}</title>
{% endblock titulo %}

{% block contenido %}
	<div class="container">
		{% if detallevideo %}
			<div class="card" style="width: 80rem;">
				<center>
					<video id="videoPlayer" style=" width:80rem; height:20rem;" controls> 
						<source src="{% url 'video:view_video' detallevideo.pk %}" type="">
							Tu navegador no soporta los videos HTML5
					</video>					
				</center>

			  <div class="card-body">
			    <h5 class="card-title">{{ detallevideo.catalog_nombre }}</h5>
			    <p class="card-text">
			    	<h6 class="h6">Sipnosis</h6>
			    	{{ detallevideo.sipnosis }}
			    </p>
			  </div>
			  <ul class="list-group list-group-flush">
			    <li class="list-group-item"><span class="h6">Autor:</span> {{ detallevideo.author }}</li>
			    <li class="list-group-item"> <span class="h6">Categoria:</span> {{ detallevideo.idcategoria }}</li>
			    <li class="list-group-item"><span class="h6">Clasificacion:</span> {{ detallevideo.idclasificacion }}</li>
			  </ul>
			</div>
		{% endif %}

		<!-- Pills navs -->
		<ul class="nav nav-pills mb-3" id="ex1" role="tablist">
			{% for k, v in temporadas.items %}
			  <li class="nav-item" role="presentation">
			  	{% ifequal k "1" %}{# verifica si la primera temporada es 1 para activar solo el primer boton los demas se desactivan #}
				    <a
				      class="nav-link active"
				      id="ex1-tab-{{ k }}"
				      data-mdb-toggle="pill"
				      href="#ex1-pills-{{ k }}"
				      role="tab"
				      aria-controls="ex1-pills-{{ k }}"
				      aria-selected="true"
				      >Temporada {{ k }}</a>
			  	}
			    {% else %}
				    <a
				      class="nav-link"
				      id="ex1-tab-{{ k }}"
				      data-mdb-toggle="pill"
				      href="#ex1-pills-{{ k }}"
				      role="tab"
				      aria-controls="ex1-pills-{{ k }}"
				      aria-selected="true"
				      >Temporada {{ k }}</a>
			    {% endifequal %}
			  </li>
		  {% endfor %}
		</ul>
		<!-- Pills navs -->

		<!-- Pills content -->
		<div class="tab-content" id="ex1-content">
		{% for k, v in temporadas.items %}
		  {% ifequal k "1" %}
		  <div class="tab-pane fade show active" id="ex1-pills-{{ k }}" role="tabpanel" aria-labelledby="ex1-tab-{{ k }}">
		  {% else %}
		  <div class="tab-pane fade" id="ex1-pills-{{ k }}" role="tabpanel" aria-labelledby="ex1-tab-{{ k }}">  
		  {% endifequal %}
      	<div class="row row-cols-1 row-cols-md-6 g-4">
        	{% for video in v %}
           	<div class="col">
              <div class="card h-100">
              	<a href="#">
                	<img
                  	src="{% url 'video:view_img_video' video.pk %}" class="card-img-top" alt="..."/>                              
                </a>
              </div>
            </div>
          {% endfor %}
       </div>
		  </div>
		{% endfor %}
		</div>
	</div>

{% endblock %}

{% block scriptjs %}
	{% load static %}
	<script type="text/javascript" src="{% static 'js/funciones_detalle_catalogo.js' %}"></script>
{% endblock scriptjs %}

media/templates/media/proces_usuario/listar_usuarios.html
{% extends "base.html" %}

{% block contenido %}
    
{% endblock %}

media/templates/media/proces_usuario/login.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block contenido %}
<div class="container">
    <form method='POST'>
        {% csrf_token %}
        {{ form|crispy }}

    <!-- 2 column grid layout for inline styling -->
    <div class="row mb-4">
        <div class="col d-flex justify-content-center">
        <!-- Checkbox -->
        <div class="form-check">
            <input
            class="form-check-input"
            type="checkbox"
            value=""
            id="form2Example34"
            checked
            />
            <label class="form-check-label" for="form2Example34"> Remember me </label>
        </div>
        </div>

        <div class="col">
        <!-- Simple link -->
        <a href="#!">Forgot password?</a>
        </div>
    </div>

    <!-- Submit button -->
    <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>

    <!-- Register buttons -->
    <div class="text-center">
        <p>Not a member? <a href="#!">Register</a></p>
        <p>or sign up with:</p>
        <button type="button" class="btn btn-primary btn-floating mx-1">
        <i class="fab fa-facebook-f"></i>
        </button>

        <button type="button" class="btn btn-primary btn-floating mx-1">
        <i class="fab fa-google"></i>
        </button>

        <button type="button" class="btn btn-primary btn-floating mx-1">
        <i class="fab fa-twitter"></i>
        </button>

        <button type="button" class="btn btn-primary btn-floating mx-1">
        <i class="fab fa-github"></i>
        </button>
    </div>
    </form>
</div>
{% endblock %}

media/templates/media/proces_usuario/logout.html
{% extends "base.html" %}

{% block contenido %}
    <div class="container">
        <div class="alert alert-primary" role="alert">
                Has cerrado session, esperamos que vuelvas pronto!
        </div>
    </div>
{% endblock %}

media/templates/media/proces_video/detalleVideo.html
{% extends "base.html" %}

{% block contenido %}
<div class="container-fluid">
			{% if detalleVideo %}
			<div class="card">
				<center><h5 class="card-header">{{ detalleVideo.cap }}</h5></center>				
				<center>
					<video id="videoPlayer" controls style="width:100%; height:100%;" > 
						<source src="{% url 'video:view_cap' detalleVideo.pk %}" type="">
							Tu navegador no soporta los videos HTML5
					</video>					
				</center>
				<div class="card-body">
					<input type="hidden" name="pk_video" id="pk_video" value="{{ detalleVideo.pk }}"> 
					<input type="hidden" name="url_view" id="url_view" value="{% url 'video:save_video_view' %}">
					<h5 class="h5">{{ detalleVideo.descripcion }}</h5>
				</div>
			</div>
			{% endif %}
		<!-- Pills navs -->
		<ul class="nav nav-pills mb-3" id="ex1" role="tablist">
			{% for k, v in temporadas.items %}
			  <li class="nav-item" role="presentation">
			  	{% ifequal k "1" %}{# verifica si la primera temporada es 1 para activar solo el primer boton los demas se desactivan #}
				    <a
				      class="nav-link active"
				      id="ex1-tab-{{ k }}"
				      data-mdb-toggle="pill"
				      href="#ex1-pills-{{ k }}"
				      role="tab"
				      aria-controls="ex1-pills-{{ k }}"
				      aria-selected="true"
				      >Temporada {{ k }}</a>
			    {% else %}
				    <a
				      class="nav-link"
				      id="ex1-tab-{{ k }}"
				      data-mdb-toggle="pill"
				      href="#ex1-pills-{{ k }}"
				      role="tab"
				      aria-controls="ex1-pills-{{ k }}"
				      aria-selected="true"
				      >Temporada {{ k }}</a>
			    {% endifequal %}
			  </li>
		  {% endfor %}
		</ul>
		<!-- Pills navs -->

		<!-- Pills content -->
		<div class="tab-content" id="ex1-content">
		{% for k, v in temporadas.items %}
		  {% ifequal k "1" %}
		  <div class="tab-pane fade show active" id="ex1-pills-{{ k }}" role="tabpanel" aria-labelledby="ex1-tab-{{ k }}">
		  {% else %}
		  <div class="tab-pane fade" id="ex1-pills-{{ k }}" role="tabpanel" aria-labelledby="ex1-tab-{{ k }}">  
		  {% endifequal %}
		  	<div class="row row-cols-1 row-cols-md-5 g-4">
			          	{% for video in v %}
			    <div class="col">
			        <div class="card">
			         	<h5 class="card-header">{{ video.cap}}</h5>
			              <a href="{% url 'video:view_video_cap' video.pk %}">
			                <img
			                  	src="{% url 'video:view_img_video' video.pk %}" class="card-img-top" alt="..."/>                              
			                </a>
			            	<div class="card-body">
			              		<h5 class="h5">{{ video.descripcion }}</h5>
			            	</div>
			        </div>
			    </div>
			          {% endfor %}
			</div>

		    </div>
			  {% endfor %}
			</div>
		</div>
</div>
{% endblock %}

{% block scriptjs %}
	{% load static %}
	<script type="text/javascript" src="{% static 'js/videos/operaciones_videos.js' %}"></script>
{% endblock %}